    = Projektauftrag LeoCode
// Metadata
:team: Besic Benjamin, Ignjatovic David, Raid Yimne, Spasenovic Bozidar
:team-leiter: Ignjatovic David
:date: 10.10.2020
:revision:  1.0
// Settings
:source-highlighter: coderay
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
// :imagesdir: images
// :sourcedir-code: src/main/java/at/htl/jdbcprimer
// :sourcedir-test: src/test/java/at/htl/jdbcprimer
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

== Projektbezeichnung
*LeoCode C#*

== Projektauftraggeber
Prof. Mag. Dr. Stütz

== Projekthintergrund
In der HTL Leonding wird besonders beim Informatikzweig (zum Teil auch in den anderen Zweigen) auf praktische Programmierübungen
Wert gelegt. +
Viele Schüler haben aber durch den Lehrplan nicht genug praktische Übung im Unterricht und kennen sich meistens nicht bei den Hausübungen aus. +
Noch dazu haben die ersten Klassen öfters Probleme mit den IDE's. Meistens haben sie keinen Zugriff oder irgendetwas hat nicht funktioniert.

== Projektergebnis

Das Ergebnis ist eine Webapp, wo die Schüler C# Coding-Übungen mit dazugehöriger Überprüfung absolvieren können.

== Projektziel

Das Ziel ist es den Schülern die Möglichkeit zu geben, Programmieren in der Sprache C# zu üben und dadurch besser im Unterricht mitzukommen.

== Projektbeschreibung
Das Projekt ist eine Webanwendung, wo der Schüler die Möglichkeit hat verschiedene Übungen für C# durchzuführen.
Der Schüler loggt sich mit seinen Schuldaten ein und kann direkt loslegen. +
Nachdem der Schüler seine Lösung ausprogrammiert hat, wird der Quellcode kompiliert und durch Tests geprüft, ob die Lösung
korrekt ist oder nicht.

CAUTION: Noch nicht fertig!

== Meilensteine

CAUTION: Noch nicht fertig!


== Freigaben

== Projektstart

05.10.2020

== Projektende

nicht festgelegt

== Projektressourcen
=== IDEA
* IntelliJ

=== Programmieren
* Quarkus
* nodeJS
* angular

=== Webapp
* Webserver
* Datenbank


CAUTION: Noch nicht fertig!

== Projektrisiken

* Zeitmangel

== Projektorganisation
* Projektmanager: {team-leiter}
* Projektstellvertreter: {team}


== Abschluss des Projektauftrags
